/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package freebox/bridge */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "archive.go"

#include "include/freebox_bridge.h"

#line 1 "cgo-generated-wrapper"

#line 3 "bridge.go"


#include "include/freebox_bridge.h"
#include <stdbool.h>

int32_t Freebox_InitDartApiDL(void* data);
bool Freebox_PostTaskProgressToDart(
    int64_t port_id,
    uint64_t task_id,
    uint8_t status,
    int64_t bytes_processed,
    int64_t total_bytes,
    double percent,
    double speed_bytes_sec,
    int64_t duration_ms,
    const uint8_t* current_item_ptr,
    int32_t current_item_len,
    const uint8_t* error_ptr,
    int32_t error_len
);

#line 1 "cgo-generated-wrapper"

#line 3 "clipboard.go"

#include "include/freebox_bridge.h"

#line 1 "cgo-generated-wrapper"

#line 3 "dedup.go"

#include "include/freebox_bridge.h"
#include <stdbool.h>

bool Freebox_PostTaskProgressToDart(
    int64_t port_id,
    uint64_t task_id,
    uint8_t status,
    int64_t bytes_processed,
    int64_t total_bytes,
    double percent,
    double speed_bytes_sec,
    int64_t duration_ms,
    const uint8_t* current_item_ptr,
    int32_t current_item_len,
    const uint8_t* error_ptr,
    int32_t error_len
);

#line 1 "cgo-generated-wrapper"

#line 3 "gdrive.go"

#include "include/freebox_bridge.h"

#line 1 "cgo-generated-wrapper"

#line 3 "media.go"

#include "include/freebox_bridge.h"

#line 1 "cgo-generated-wrapper"

#line 3 "memory.go"

#include <stdlib.h>
#include <stdint.h>
#include "include/freebox_bridge.h"

#line 1 "cgo-generated-wrapper"

#line 3 "search.go"

#include "include/freebox_bridge.h"

#line 1 "cgo-generated-wrapper"

#line 3 "servers.go"

#include "include/freebox_bridge.h"

#line 1 "cgo-generated-wrapper"

#line 3 "signer.go"

#include "include/freebox_bridge.h"

#line 1 "cgo-generated-wrapper"

#line 3 "stream.go"

#include "include/freebox_bridge.h"

#line 1 "cgo-generated-wrapper"

#line 3 "tasks.go"

#include "include/freebox_bridge.h"
#include <stdbool.h>

bool Freebox_PostTaskProgressToDart(
    int64_t port_id,
    uint64_t task_id,
    uint8_t status,
    int64_t bytes_processed,
    int64_t total_bytes,
    double percent,
    double speed_bytes_sec,
    int64_t duration_ms,
    const uint8_t* current_item_ptr,
    int32_t current_item_len,
    const uint8_t* error_ptr,
    int32_t error_len
);

#line 1 "cgo-generated-wrapper"

#line 3 "telegram.go"

#include "include/freebox_bridge.h"

#line 1 "cgo-generated-wrapper"

#line 3 "vfs.go"

#include "include/freebox_bridge.h"
#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern uint64_t Freebox_ArchiveCompress(uint64_t engineHandle, FreeboxArchiveFormat formatCode, uint8_t* srcPathPtr, int32_t srcPathLen, uint8_t* dstPathPtr, int32_t dstPathLen, uint8_t* passPtr, int32_t passLen, int64_t dartPort, FreeboxResultC* outResult);
extern uint64_t Freebox_ArchiveExtract(uint64_t engineHandle, uint8_t* srcArchivePtr, int32_t srcArchiveLen, uint8_t* dstDirPtr, int32_t dstDirLen, uint8_t* passPtr, int32_t passLen, int64_t dartPort, FreeboxResultC* outResult);
extern int32_t Freebox_ArchivePreview(uint64_t engineHandle, uint8_t* archivePathPtr, int32_t archivePathLen, uint8_t* passPtr, int32_t passLen, FreeboxResultC* outResult);
extern GoInt32 Freebox_InitDartApi(void* data);
extern GoUint64 Freebox_InitEngine(uint8_t* dbPathPtr, int32_t dbPathLen, uint8_t* passphrasePtr, int32_t passphraseLen, int32_t maxWorkers, uint8_t* streamPortPtr, int32_t streamPortLen, FreeboxResultC* outResult);
extern uint8_t Freebox_RegisterDartPort(uint64_t engineHandle, int64_t dartPort);
extern uint8_t Freebox_CloseEngine(uint64_t engineHandle);
extern uint8_t Freebox_ClipboardCopy(uint64_t engineHandle, uint8_t* pathPtr, int32_t pathLen, FreeboxResultC* outResult);
extern uint8_t Freebox_ClipboardCut(uint64_t engineHandle, uint8_t* pathPtr, int32_t pathLen, FreeboxResultC* outResult);
extern uint64_t Freebox_ClipboardPaste(uint64_t engineHandle, uint8_t* dstDirPtr, int32_t dstDirLen, int64_t dartPort, FreeboxResultC* outResult);
extern uint8_t Freebox_ClipboardClear(uint64_t engineHandle);
extern int32_t Freebox_ClipboardCount(uint64_t engineHandle);
extern uint64_t Freebox_DedupScan(uint64_t engineHandle, uint8_t* rootPathPtr, int32_t rootPathLen, FreeboxDedupMethod methodCode, FreeboxDedupAction actionCode, FreeboxDedupKeepPolicy keepPolicyCode, int64_t minSize, int32_t maxWorkers, int64_t dartPort, FreeboxResultC* outResult);
extern uint8_t Freebox_GDriveAuthorize(uint64_t engineHandle, uint8_t* clientIDPtr, int32_t clientIDLen, uint8_t* clientSecPtr, int32_t clientSecLen, uint8_t* credsJSONPtr, int32_t credsJSONLen, int32_t port, uint8_t* callbackPathPtr, int32_t callbackPathLen, uint8_t** outTokenJSONPtr, int32_t* outTokenJSONLen, FreeboxResultC* outResult);
extern uint8_t Freebox_GDriveMount(uint64_t engineHandle, uint8_t* mountNamePtr, int32_t mountNameLen, uint8_t* clientIDPtr, int32_t clientIDLen, uint8_t* clientSecPtr, int32_t clientSecLen, uint8_t* tokenJSONPtr, int32_t tokenJSONLen, uint8_t* rootFolderIDPtr, int32_t rootFolderIDLen, FreeboxResultC* outResult);
extern uint8_t Freebox_GenerateThumbnail(uint64_t engineHandle, uint8_t* srcPathPtr, int32_t srcPathLen, int32_t width, int32_t height, int32_t quality, uint8_t** outDataPtr, int32_t* outDataLen, FreeboxResultC* outResult);
extern uint8_t Freebox_ExtractMetadata(uint64_t engineHandle, uint8_t* srcPathPtr, int32_t srcPathLen, FreeboxMediaMetaC* outMeta, FreeboxResultC* outResult);
extern void Freebox_FreeBuffer(void* ptr);
extern uint64_t Freebox_Search(uint64_t engineHandle, uint8_t* rootPathPtr, int32_t rootPathLen, uint8_t* namePatternPtr, int32_t namePatternLen, uint8_t* contentPatternPtr, int32_t contentPatternLen, uint8_t* replacementPtr, int32_t replacementLen, FreeboxSearchMatchType matchTypeCode, FreeboxSearchTarget targetCode, uint8_t isReplace, uint8_t caseSensitive, int64_t dartPort, FreeboxResultC* outResult);
extern uint8_t Freebox_StartAPIServer(uint64_t engineHandle, uint8_t* portPtr, int32_t portLen, FreeboxResultC* outResult);
extern uint8_t Freebox_StopAPIServer(uint64_t engineHandle);
extern uint8_t Freebox_StartHTTPServer(uint64_t engineHandle, uint8_t* portPtr, int32_t portLen, uint8_t* rootDirPtr, int32_t rootDirLen, FreeboxResultC* outResult);
extern uint8_t Freebox_StopHTTPServer(uint64_t engineHandle);
extern uint8_t Freebox_StartFTPServer(uint64_t engineHandle, uint8_t* portPtr, int32_t portLen, uint8_t* rootDirPtr, int32_t rootDirLen, FreeboxResultC* outResult);
extern uint8_t Freebox_StopFTPServer(uint64_t engineHandle);
extern uint8_t Freebox_StartDLNAServer(uint64_t engineHandle, uint8_t* friendlyNamePtr, int32_t friendlyNameLen, uint8_t* portPtr, int32_t portLen, uint8_t* rootDirPtr, int32_t rootDirLen, FreeboxResultC* outResult);
extern uint8_t Freebox_StopDLNAServer(uint64_t engineHandle);
extern uint8_t Freebox_SignFile(uint64_t engineHandle, uint8_t* filePathPtr, int32_t filePathLen, uint8_t* privKeyPEMPtr, int32_t privKeyPEMLen, uint8_t** outSigPtr, int32_t* outSigLen, FreeboxResultC* outResult);
extern uint8_t Freebox_VerifyFileSignature(uint64_t engineHandle, uint8_t* filePathPtr, int32_t filePathLen, uint8_t* sigHexPtr, int32_t sigHexLen, uint8_t* pubKeyPEMPtr, int32_t pubKeyPEMLen, FreeboxResultC* outResult);
extern uint8_t Freebox_RegisterStream(uint64_t engineHandle, uint8_t* namePtr, int32_t nameLen, uint8_t* urlPtr, int32_t urlLen, FreeboxResultC* outResult);
extern uint8_t Freebox_UnregisterStream(uint64_t engineHandle, uint8_t* namePtr, int32_t nameLen);
extern uint64_t Freebox_SubmitTaskBytes(uint64_t engineHandle, FreeboxTaskType taskTypeCode, uint8_t* srcPtr, int32_t srcLen, uint8_t* dstPtr, int32_t dstLen, uint8_t* dataPtr, int32_t dataLen, int32_t priority, int64_t dartPort, FreeboxResultC* outResult);
extern uint64_t Freebox_SubmitTaskRunes(uint64_t engineHandle, FreeboxTaskType taskTypeCode, uint32_t* srcRunesPtr, int32_t srcRunesLen, uint32_t* dstRunesPtr, int32_t dstRunesLen, int32_t priority, int64_t dartPort, FreeboxResultC* outResult);
extern uint8_t Freebox_PauseTask(uint64_t engineHandle, uint64_t uintTaskID);
extern uint8_t Freebox_ResumeTask(uint64_t engineHandle, uint64_t uintTaskID);
extern uint8_t Freebox_CancelTask(uint64_t engineHandle, uint64_t uintTaskID);
extern uint8_t Freebox_GetTaskProgress(uint64_t engineHandle, uint64_t uintTaskID, FreeboxTaskProgressC* outProgress);
extern uint8_t Freebox_GetTaskRecord(uint64_t engineHandle, uint64_t uintTaskID, FreeboxTaskRecordC* outRecord);
extern uint8_t Freebox_TelegramListSessions(uint64_t engineHandle, FreeboxResultC* outResult);
extern uint8_t Freebox_TelegramRemoveSession(uint64_t engineHandle, int64_t accountID, FreeboxResultC* outResult);
extern uint8_t Freebox_Mount(uint64_t engineHandle, uint8_t* namePtr, int32_t nameLen, uint8_t* typePtr, int32_t typeLen, uint8_t* pathPtr, int32_t pathLen, uint8_t readOnly, FreeboxResultC* outResult);
extern uint8_t Freebox_Unmount(uint64_t engineHandle, uint8_t* namePtr, int32_t nameLen);
extern uint8_t Freebox_ListDir(uint64_t engineHandle, uint8_t* pathPtr, int32_t pathLen, FreeboxFileInfoC** outFilesArray, int32_t* outCount, FreeboxResultC* outResult);
extern uint8_t Freebox_ReadFileBytes(uint64_t engineHandle, uint8_t* pathPtr, int32_t pathLen, uint8_t** outDataPtr, int32_t* outDataLen, FreeboxResultC* outResult);
extern uint8_t Freebox_WriteFileBytes(uint64_t engineHandle, uint8_t* pathPtr, int32_t pathLen, uint8_t* dataPtr, int32_t dataLen, FreeboxResultC* outResult);

#ifdef __cplusplus
}
#endif
